---
title: "Regression"
output: 
  html_document:
    toc: true
    toc_float: 
      toc_collapsed: true
    toc_depth: 5
    code_folding: hide
---

```{r message = FALSE, warning = FALSE}
library(tidyverse)
library(readxl)
library(car)
```


```{r message = FALSE, warning = FALSE}
url_2012 = "https://raw.githubusercontent.com/YijiaJiang/p8105_final_project_data/main/rat_2012.csv"
rat_2012 = read_csv(url(url_2012)) 
url_2013 = "https://raw.githubusercontent.com/YijiaJiang/p8105_final_project_data/main/rat_2013.csv"
rat_2013 = read_csv(url(url_2013)) 
url_2014 = "https://raw.githubusercontent.com/YijiaJiang/p8105_final_project_data/main/rat_2014.csv"
rat_2014 = read_csv(url(url_2014)) 
url_2015 = "https://raw.githubusercontent.com/YijiaJiang/p8105_final_project_data/main/rat_2015.csv"
rat_2015 = read_csv(url(url_2015)) 
url_2016 = "https://raw.githubusercontent.com/YijiaJiang/p8105_final_project_data/main/rat_2016.csv"
rat_2016 = read_csv(url(url_2016)) 
url_2017 = "https://raw.githubusercontent.com/YijiaJiang/p8105_final_project_data/main/rat_2017.csv"
rat_2017 = read_csv(url(url_2017)) 
url_2018 = "https://raw.githubusercontent.com/YijiaJiang/p8105_final_project_data/main/rat_2018.csv"
rat_2018 = read_csv(url(url_2018)) 
url_2019 = "https://raw.githubusercontent.com/YijiaJiang/p8105_final_project_data/main/rat_2019.csv"
rat_2019 = read_csv(url(url_2019)) 
url_2020 = "https://raw.githubusercontent.com/YijiaJiang/p8105_final_project_data/main/rat_2020.csv"
rat_2020 = read_csv(url(url_2020)) 
url_2021 = "https://raw.githubusercontent.com/YijiaJiang/p8105_final_project_data/main/rat_2021.csv"
rat_2021 = read_csv(url(url_2021)) 
```

```{r}
rat = bind_rows(rat_2012, rat_2013, rat_2014, rat_2015, rat_2016, rat_2017, rat_2018, rat_2019, rat_2020, rat_2021) %>%
  select(-...1) %>%
   mutate(inspection_month_n = case_when(inspection_month == "Jan" ~ 1,
                                   inspection_month == "Feb" ~ 2,
                                   inspection_month == "Mar" ~ 3,
                                   inspection_month == "Apr" ~ 4,
                                   inspection_month == "May" ~ 5,
                                   inspection_month == "Jun" ~ 6,
                                   inspection_month == "Jul" ~ 7,
                                   inspection_month == "Aug" ~ 8,
                                   inspection_month == "Sep" ~ 9,
                                   inspection_month == "Oct" ~ 10,
                                   inspection_month == "Nov" ~ 11,
                                   inspection_month == "Dec" ~ 12)) %>%
  mutate(date = paste(inspection_year, inspection_month_n, inspection_day, sep = "-")) %>%
  mutate(date = as.Date(date,format = "%Y-%m-%d")) %>% 
  mutate(inspection_ym = paste(inspection_year, inspection_month_n, sep = "-")) %>%
  mutate(covid_yn = case_when(date < "2020-02-29" ~ 0,
                              TRUE ~ 1)) %>%
  separate(inspection_time, into = c("hour", "minute", "second")) %>%
  mutate(hour = as.numeric(hour)) %>%
  mutate(inspection_daytime = case_when(
      hour < 6 | hour >= 18 ~ "Night",
      hour >= 6 & hour < 12 ~ "Morning",
      hour >= 12 & hour < 18 ~ "Afternoon"))
  
#%>%  filter(result != "Passed")
```

## Variable selection
 
```{r, message = FALSE, warning = FALSE,comment = FALSE}
cases = rat %>% 
  select(borough, inspection_ym, inspection_month, covid_yn, prcp, snow, snwd, tmin, tmax) %>% 
  group_by(inspection_ym, borough) %>% 
  add_count(borough, inspection_ym, name = "borough_monthly_cases") %>%
  select(-prcp, -snow, -snwd, -tmin, -tmax)


rat_tidy = rat %>% 
  select(borough, inspection_ym, inspection_month, covid_yn, prcp, snow, snwd, tmin, tmax) %>%
  mutate(borough = as.factor(borough), 
         inspection_month = as.factor(inspection_month), 
         covid_yn = as.factor(covid_yn),
         prcp = as.numeric(prcp), 
         snow = as.numeric(snow), 
         snwd = as.numeric(snwd),
         tmin = as.numeric(tmin), 
         tmax = as.numeric(tmax)) %>% 
  group_by(inspection_ym, borough) %>% summarise(avg_prcp = mean(prcp),
                                                 avg_snow = mean(snow),
                                                 avg_snwd = mean(snwd),
                                                 avg_tmin = mean(tmin),
                                                 avg_tmax = mean(tmax))



cases_borough_monthly = merge(x = rat_tidy, y = cases, by = c("inspection_ym", "borough")) %>% distinct() 
```


```{r, include=FALSE}
# export the tidied dataset of modelling for shiny
write.csv(rat_tidy,"./rat_app/www/rat_tidy.csv")
```


## Linear Regression Model

```{r, message = FALSE, warning = FALSE,comment = FALSE}
  
model_linear_original = lm(borough_monthly_cases ~ inspection_month + borough + covid_yn + avg_prcp + avg_snwd + avg_tmax, data = cases_borough_monthly) 
broom::tidy(model_linear_original) %>% 
  knitr::kable()
summary(model_linear_original)

model_linear = step(model_linear_original, direction = "backward")
broom::tidy(model_linear) %>% 
  knitr::kable()


summary(model_linear)
```

## Model diagnostics

```{r, message = FALSE, warning = FALSE,comment = FALSE}
set.seed(100)
par(mfrow=c(2,2))
plot(model_linear)
anova(model_linear)
```


```{r}

outlierTest(model_linear)

durbinWatsonTest(model_linear)

vif(model_linear)
```



## Logistic Regression Model

We set the Result variable as the binary outcome. Passed(0) means none was inspected.

```{r, message = FALSE, warning = FALSE,comment = FALSE}

rat_binary = rat %>% 
  select(result, borough, inspection_month, inspection_daytime, covid_yn, prcp, snow, snwd, tmin, tmax) %>%
  mutate(inspection_result = case_when(
    result == "Passed" ~ 0, 
    TRUE ~ 1)) %>%
  mutate(inspection_result = as.factor(inspection_result), 
         borough = as.factor(borough),
         covid_yn = as.factor(covid_yn),
         inspection_month = as.factor(inspection_month), 
         inspection_daytime = as.factor(inspection_daytime), 
         prcp = as.numeric(prcp), 
         snow = as.numeric(snow), 
         snwd = as.numeric(snwd),
         tmin = as.numeric(tmin), 
         tmax = as.numeric(tmax)) %>%
  distinct()
```



```{r}
model_logit_original = glm(inspection_result ~ inspection_month + borough + inspection_daytime + prcp + snow + snwd + tmin + tmax, data = rat_binary, family="binomial")

model_logit = step(model_logit_original, direction = "backward")
broom::tidy(model_linear) %>% 
  knitr::kable()

summary(model_logit)
anova(model_logit)
```


```{r, message = FALSE, warning = FALSE,comment = FALSE}
set.seed(100)
par(mfrow=c(2,2))
plot(model_logit)
anova(model_logit)

```
## Merge with Covid-19


```{r}

url_covid = "https://raw.githubusercontent.com/YijiaJiang/p8105_final_project_data/main/rat_weather_covid.csv"
rat_covid = read_csv(url_covid)


rat_covid = rat_covid %>%
  mutate(inspection_month_n = case_when(inspection_month == "Jan" ~ 1,
                                   inspection_month == "Feb" ~ 2,
                                   inspection_month == "Mar" ~ 3,
                                   inspection_month == "Apr" ~ 4,
                                   inspection_month == "May" ~ 5,
                                   inspection_month == "Jun" ~ 6,
                                   inspection_month == "Jul" ~ 7,
                                   inspection_month == "Aug" ~ 8,
                                   inspection_month == "Sep" ~ 9,
                                   inspection_month == "Oct" ~ 10,
                                   inspection_month == "Nov" ~ 11,
                                   inspection_month == "Dec" ~ 12)) %>%
  mutate(date = paste(inspection_year, inspection_month_n, inspection_day, sep = "-"))%>%
  mutate(date = as.Date(date,format = "%Y-%m-%d"))

```
